<script>
    require([
        'Magento_Ui/js/lib/validation/validator',
        'jquery',
        'jquery/ui',
        'mage/translate'
    ], function (validator, $) {
        // setTimeout(() => {
        //     $('[name="textarea_formbuilder"]').val('Please Wait...');
        // }, 5);
        setTimeout(() => {
            var getFormBuilder = $('[name="textarea_formbuilder"]');
            var disableAttributes = {
                disabledAttrs: [
                    'inline',
                    'access',
                    'toggle',
                    'other',
                ],
                disabledSubtypes: {
                    text: ['color', 'tel'],
                    date: ['time'],
                    textarea: ['tinymce', 'quill']
                },
                typeUserEvents: {
                    '*': {
                            onadd: function(fld) {
                            var nameAttrVal = $('.fld-name').val();
                            var nameAttrText = $('.fld-name');
                            if (nameAttrVal) {
                                setTimeout(() => {
                                    nameAttrText.val('input_field');
                                }, 1000);
                            } else {
                                console.log("match not found");
                            }
                        }
                    },
                },
                showActionButtons: true,
                scrollToFieldOnAdd: false
            }
            var formBuilder = $(getFormBuilder).formBuilder(disableAttributes);
            $(document).on('click', '.formSave', function (event) {
                // console.log(formBuilder.actions.getData());
                $('[name="formbuilder_data"]').val(formBuilder.actions.getData('json')).trigger('change');
            });

            formBuilder.promise.then(function () {
                console.log("formBuilder has been initialized");

                var url_my_string = "<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>";

                try {
                    var myUrl = new URL(url_my_string);
                    console.log("Full pathname:", myUrl.pathname);

                    var segments = myUrl.pathname.split('/');
                    var id = findNumericSegment(segments);
                    console.log("id:", id);

                    if (id) {
                        console.log($('[name="formbuilder_data"]').val());
                        formBuilder.actions.setData($('[name="formbuilder_data"]').val());
                    }

                } catch (error) {
                    console.error("Error parsing URL:", error);
                }
            });

            function findNumericSegment(segments) {
                for (var i = segments.length - 1; i >= 0; i--) {
                    var segment = segments[i];
                    if (!isNaN(segment) && segment.trim() !== '') {
                        return segment;
                    }
                }
                return null;
            }
        }, 200);

        validator.addRule(
            'custom-validation',
            function (value) {
                $(document).on('click', '.formSave', function () {
                    console.log('button clicked');
                    var nameFieldVal = $('.fld-name').val();
                    var nameField = $('.fld-name');
                    if (nameFieldVal.includes('_')) {
                        console.log("it has an underscore with name");
                        $(nameField).closest('li').css('border', '1px solid red');
                    } else {
                        return true;
                    }
                })
            }, $.mage.__('Some of name attribute has an underscore ( __ ) within its value.')
        );
    });
</script>
